import type { Workspace } from "./types";

export type FlowNode = {
  key: string;
  title: string;
  kind: string;
  description: string;
  /** Rendered as a dashed node (conditional branch). */
  conditional?: boolean;
  /** Rendered as a pill (terminal node). */
  terminal?: boolean;
};

export const FLOW_NODES: FlowNode[] = [
  {
    key: "bullets",
    title: "Selected Big CV bullets + job",
    kind: "Input",
    description:
      "The evidence base. Parsed bullets you have toggled on, plus the target job description and your intent. This is the only source of truth for the tailoring.",
  },
  {
    key: "jev",
    title: "JEV capability plan",
    kind: "Routing",
    conditional: true,
    description:
      "JevRouter receives the capability manifests and the request, then returns which capability handles each step with probabilities, confidence, risk and confirmation gates.",
  },
  {
    key: "research",
    title: "Optional company research",
    kind: "Research",
    conditional: true,
    description:
      "Runs only when the JEV plan selects company_research. Exa if EXA_API_KEY is set, otherwise a model knowledge brief. Its output is context for generation, never CV evidence.",
  },
  {
    key: "generate",
    title: "Generate tailored CV",
    kind: "Generation",
    description:
      "The LLM rewrites selected bullets against the job and intent, keeps every number, mirrors the job language, and traces each bullet back to a Big CV evidence id.",
  },
  {
    key: "assess",
    title: "Assess quality",
    kind: "Evaluation",
    description:
      "A second pass scores the tailored CV against the job on six dimensions, computes keyword coverage, and returns concrete edits.",
  },
  {
    key: "output",
    title: "CV + quality output",
    kind: "Output",
    terminal: true,
    description:
      "The tailored CV and its quality report. Copy or export as JSON, and iterate by toggling bullets or changing the intent.",
  },
];

export type NodeStatus = "idle" | "running" | "done" | "skipped" | "error";

export type NodeState = {
  status: NodeStatus;
  lines: string[];
};

const STATUS_ORDER = ["bullets", "jev", "research", "generate", "assess", "output"];

/** Live state for one node, derived from the workspace. */
export function nodeState(
  key: string,
  ws: Workspace,
  bulletCount: number,
): NodeState {
  const running = (cap: string) => ws.activeCapability === cap;

  if (ws.status === "error" && ws.pipelineErrorNode === key) {
    return { status: "error", lines: [ws.error || "This step failed."] };
  }

  switch (key) {
    case "bullets":
      return {
        status: bulletCount > 0 ? "done" : "idle",
        lines: [
          `${bulletCount} bullet${bulletCount === 1 ? "" : "s"} selected`,
          ws.job.title ? `Target: ${ws.job.title}${ws.job.company ? ` · ${ws.job.company}` : ""}` : "No job selected",
          ws.intent ? `Intent: ${ws.intent}` : "No intent set",
        ],
      };
    case "jev": {
      if (running("cv_generate") || ws.jev) {
        return {
          status: ws.jev ? "done" : "running",
          lines: ws.jev
            ? [
                `transport ${ws.jev.transport} · ${ws.jev.provider}`,
                `plan: ${ws.jev.executionPlan.join(" \u2192 ")}`,
                ws.jev.steps[0]?.fallback?.reason
                  ? `fallback: ${ws.jev.steps[0].fallback.reason}`
                  : `status: ${ws.jev.status}`,
              ]
            : ["Waiting for JevRouter…"],
        };
      }
      if (ws.status === "routing") return { status: "running", lines: ["Routing with JevRouter…"] };
      return { status: "idle", lines: ["Not routed yet. Run the agent."] };
    }
    case "research": {
      const selected = ws.jev?.executionPlan.includes("company_research");
      if (running("company_research")) return { status: "running", lines: ["Researching the company…"] };
      if (ws.research) return { status: "done", lines: [ws.research.slice(0, 220)] };
      if (ws.jev && !selected)
        return { status: "skipped", lines: ["JEV did not select this capability for the plan."] };
      return { status: "idle", lines: ["Runs only if the JEV plan selects it."] };
    }
    case "generate": {
      if (running("cv_generate")) return { status: "running", lines: ["Tailoring the CV…"] };
      if (ws.cv)
        return {
          status: "done",
          lines: [
            `${ws.cv.bullets.length} tailored bullets`,
            `${ws.cv.skills.length} skills surfaced`,
            ws.usedMock ? "generated by the deterministic mock" : "generated by the live model",
          ],
        };
      return { status: "idle", lines: ["Not generated yet."] };
    }
    case "assess": {
      if (running("cv_assess")) return { status: "running", lines: ["Scoring the CV…"] };
      if (ws.assessment)
        return {
          status: "done",
          lines: [
            `overall ${ws.assessment.overall}/100`,
            `${ws.assessment.matchedKeywords.length} matched · ${ws.assessment.missingKeywords.length} missing keywords`,
            ws.assessment.verdict,
          ],
        };
      return { status: "idle", lines: ["Not assessed yet."] };
    }
    case "output": {
      const ready = Boolean(ws.cv && ws.assessment);
      return {
        status: ws.status === "error" ? "error" : ready ? "done" : "idle",
        lines: ready
          ? [`Quality ${ws.assessment!.overall}/100`, "Ready to copy or export"]
          : ["Complete the pipeline to produce output."],
      };
    }
    default:
      return { status: "idle", lines: [] };
  }
}

/** The node the pipeline is currently working on, for auto-selection. */
export function activeNodeKey(ws: Workspace): string {
  if (ws.status === "error" && ws.pipelineErrorNode) return ws.pipelineErrorNode;
  if (ws.status === "routing") return "jev";
  if (ws.activeCapability === "company_research") return "research";
  if (ws.activeCapability === "cv_generate" || ws.status === "generating") return "generate";
  if (ws.activeCapability === "cv_assess" || ws.status === "assessing") return "assess";
  if (ws.status === "done") return "output";
  return "bullets";
}

export const FLOW_KEYS = STATUS_ORDER;
